### ISSUE TITLE
linksrus - did you manage to deploy 03-linksrus-monolith from chapter 10 hands on software engineering with go?

### ISSUE THREAD

**Issue by igavrysh** [enesanbar/workspace#1]
I am experimenting with book's code and recently was faced with challenge of deploying monolith to k8s. 

I use slightly updated minikube version: [link](https://github.com/igavrysh/linksrus/blob/main/k8s/Makefile#L21-L39) as the version in the book was not working in my case.

My version of [03-linksrus-monolith.yaml](https://github.com/enesanbar/workspace/blob/6046937f64c006972a8b17ccbec1f7246aec1845/golang/projects/linksrus/cmd/monolith/k8s/03-linksrus-monolith.yaml)

Direct docker deployment with in-memory db etc. went fine, however when I try to deploy StatefulSet, I receive the error:
```
 | Error from server (BadRequest): error when creating "03-linksrus-monolith.yaml": admission 
webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "_" and path "/" is 
already defined in ingress linksrus/linksrus-ingress
make: *** [Makefile:58: deploy] Error 1
```
[more details here](https://github.com/PacktPublishing/Hands-On-Software-Engineering-with-Golang/issues/15)

Did you mange to deploy this version?

**Comment by enesanbar** [comment]
yeah, it's been a while, but I don't remember having any issues deploying both monolith and microservices. your problem seems to be related to duplicate definition of ingress resource in different namespaces.
